name: "001helloworld"

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  say-hello_job:
    runs-on: windows-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"